version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mavunosmart
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=moracha100

volumes:
  postgres_data:
