# Generated by Django 5.0.6 on 2024-05-29 12:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('size', models.FloatField(help_text='Size of the farm in acres')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarbonCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(help_text='Amount of carbon credits in tons')),
                ('verified', models.BooleanField(default=False)),
                ('date_verified', models.DateField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_credits', to='mavuno_smart.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(default='unknown', max_length=100)),
                ('area', models.FloatField(default=0.0)),
                ('yield_amount', models.FloatField(default=0.0)),
                ('date_planted', models.DateField(default=django.utils.timezone.now)),
                ('date_harvested', models.DateField(blank=True, null=True)),
                ('carbon_sequestered', models.FloatField(default=0.0, help_text='Carbon sequestered in tons')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farm_data', to='mavuno_smart.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FarmMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_data', models.TextField()),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mavuno_smart.farm')),
            ],
        ),
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_listed', models.DateField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('carbon_credits', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_listing', to='mavuno_smart.carboncredits')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_purchased', models.FloatField(help_text='Amount of carbon credits purchased in tons')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_purchased', models.DateField(auto_now_add=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('market_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='mavuno_smart.marketlisting')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('contact_number', models.CharField(blank=True, default='', max_length=15)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_verified', models.DateField(auto_now_add=True)),
                ('verification_report', models.TextField()),
                ('carbon_credits', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='mavuno_smart.carboncredits')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
