# Generated by Django 5.0.6 on 2024-05-21 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('mavuno_smart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmdata',
            name='data',
        ),
        migrations.AddField(
            model_name='farmdata',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='crop_type',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='date_harvested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmdata',
            name='date_planted',
            field=models.DateField(default= django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmdata',
            name='farm_name',
            field=models.CharField(default='ukunda', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmdata',
            name='location',
            field=models.CharField(default='Likoni', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmdata',
            name='yield_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='farmdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmdata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
