 # Generated by Django 5.0.6 on 2024-05-21 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavuno_smart', '0002_remove_farmdata_data_farmdata_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmdata',
            name='date_planted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
